# Generated by Django 4.0.4 on 2022-04-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='user@gmail.com', max_length=254)),
                ('task', models.CharField(max_length=100000)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
