# Generated by Django 3.2.6 on 2021-11-06 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='due_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
