# Generated by Django 3.2.6 on 2021-11-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_feature_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='due_date',
            field=models.DateField(),
        ),
    ]
