# Generated by Django 4.0.2 on 2022-03-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211110_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=1000)),
                ('buyingprice', models.IntegerField()),
                ('buyingdate', models.DateField()),
                ('sellingprice', models.IntegerField()),
                ('sellingdate', models.DateField()),
                ('profit', models.IntegerField()),
                ('loss', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
